CREATE DATABASE IF NOT EXISTS five9_backup CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

USE five9_backup;

CREATE TABLE IF NOT EXISTS calls_five9_backup (
  call_id VARCHAR(64) NOT NULL,
  agent_id VARCHAR(128) DEFAULT NULL,
  agent_first_name VARCHAR(64) DEFAULT NULL,
  agent_last_name VARCHAR(64) DEFAULT NULL,
  event_dir VARCHAR(32) DEFAULT NULL,
  start_time DATETIME DEFAULT NULL,
  end_time DATETIME DEFAULT NULL,
  duration_sec INT DEFAULT NULL,
  ani VARCHAR(32) DEFAULT NULL,
  dnis VARCHAR(32) DEFAULT NULL,
  result_code VARCHAR(32) DEFAULT NULL,
  screen_capture_type VARCHAR(32) DEFAULT NULL,
  raw_json LONGTEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(raw_json)),
  created_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (call_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
